SET client_encoding = 'UTF8';

CREATE TABLE DECHET_VERSION (
	ID_VERSION SERIAL NOT NULL,
	NUMERO VARCHAR(32) NOT NULL,
	DATE_MAJ TIMESTAMP NOT NULL,
	CONSTRAINT PK_VERSION PRIMARY KEY (ID_VERSION)
);

INSERT INTO version (NUMERO, DATEMAJ) VALUES (1.0, CURRENT_TIMESTAMP);